project:
  type: website
  output-dir: docs

website:
  title: "MRB"
  navbar:
    logo: /files/logo-mrb.png
    href: index.qmd
    left:
      - href: index.qmd
        text: Home
      - href: members.qmd
        text: Members
      - href: setup.qmd
        text: Set-up
      - href: template.qmd
        text: Template
      - href: events.qmd
        text: Events
      - href: materials.qmd
        text: Materials
        
        

format:
  html:
    link-external-icon: true
    link-external-newwindow: true
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true


