project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    logo: /files/logo-mrb.png
    href: index.qmd
    left:
      - href: index.qmd
        text: home
      - href: members.qmd
        text: members
      - href: setup.qmd
        text: set-up
      - href: events.qmd
        text: events
      - href: materials.qmd
        text: materials
      - href: template.qmd
        text: template  
        

format:
  html:
    link-external-icon: true
    link-external-newwindow: true
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true


