project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    logo: /files/logo-mrb.png
    href: index.qmd
    left:
      - href: index.qmd
        text: home
      - href: membri.qmd
        text: membri
      - href: setup.qmd
        text: setup
      - href: eventi.qmd
        text: eventi
      - href: materiali.qmd
        text: materiali
        

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true


