project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    logo: /files/logo-mrb.bmp
    href: index.qmd
    left:
      - href: index.qmd
        text: home
      - href: iniziative.qmd
        text: iniziative
        

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true


