project:
  type: website
  output-dir: docs

website:
  title: "Methodological Review Board"
  navbar:
    left:
      - href: index.qmd
        text: home
      - href: iniziative.qmd
        text: iniziative
        

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true


