---
toc: false
include-in-header: files/header.html
title: ""
---

# Membri del MRB

## Responsabili del progetto

- Prof. Gianmarco Altoè, Dipartimento di Psicologia dello Sviluppo e della Socializzazione
- Prof. Tatiana Marci, Dipartimento di Psicologia dello Sviluppo e della Socializzazione
- Prof. Massimiliano Pastore, Dipartimento di Psicologia dello Sviluppo e della Socializzazione


## Set-up team

- Dr. Giulia Calignano, Dipartimento di Psicologia dello Sviluppo e della Socializzazione
- Laura Sità, Dipartimento di Psicologia dello Sviluppo e della Socializzazione


## Consulenti e collaboratori

- Irene Alfarone, Institut für Psychologie – Universität Innsbruck
- Prof. Massimo Grassi, Dipartimento di Psicologia Generale
- Prof. Daniël Lakens, Human-Technology Interaction group – Eindhoven University of Technology 
- Matteo Manente, Dipartimento di Psicologia dello Sviluppo e della Socializzazione
- Ambra Perugini, Dipartimento di Psicologia dello Sviluppo e della Socializzazione
- Prof. Enrico Toffalini, Dipartimento di Psicologia Generale

## Team per lo studio pilota

Oltre ai responsabili del progetto e al team di set-up, contribuirano all’implementazione del MRB su uno studio pilota:

- Prof. Francesco Vespignani, Dipartimento di Psicologia dello Sviluppo e della Socializzazione
- Prof. Stefano Noventa, Dipartimento di Psicologia Generale
- Prof. Giovanni Bruno, Dipartimento di Psicologia Generale
- Prof. Giorgio Arcara, Dipartimento di Psicologia Generale
- Prof. Fabio Masina, Dipartimento di Psicologia Generale
- Prof. Antonio Maffei, Dipartimento di Psicologia dello Sviluppo e della Socializzazione
- Dr. Margherita Calderan, Dipartimento di Psicologia Generale
- Dr. Tommaso Ferraco, Dipartimento di Psicologia Generale
- Dr. Filippo Gambarota, Dipartimento di Psicologia dello Sviluppo e della Socializzazione
- Matteo Manente, Dipartimento di Psicologia dello Sviluppo e della Socializzazione
- Ambra Perugini, Dipartimento di Psicologia dello Sviluppo e della Socializzazione
- Prof. Enrico Toffalini, Dipartimento di Psicologia Generale
