---
toc: false
include-in-header: files/header.html
title: ""
---

<div style="text-align: justify;">

# MRB Members

## Project Coordinators

- Prof. Gianmarco Altoè, Department of Developmental and Social Psychology  
- Prof. Tatiana Marci, Department of Developmental and Social Psychology  
- Prof. Massimiliano Pastore, Department of Developmental and Social Psychology  

## Set-up Team

- Dr. Giulia Calignano, Department of Developmental and Social Psychology  
- Laura Sità, Department of Developmental and Social Psychology  

## Advisors and Collaborators

- Irene Alfarone, Institut für Psychologie – Universität Innsbruck  
- Prof. Massimo Grassi, Department of General Psychology  
- Prof. Daniël Lakens, Human-Technology Interaction Group – Eindhoven University of Technology  
- Matteo Manente, Department of Developmental and Social Psychology  
- Ambra Perugini, Department of Developmental and Social Psychology  
- Prof. Enrico Toffalini, Department of General Psychology  

## Pilot Study Team

In addition to the project coordinators and the set-up team, the following members from the School of Psychology at the University of Padova will take part in the implementation of the MRB as part of a pilot study:

- Prof. Francesco Vespignani, Department of Developmental and Social Psychology  
- Prof. Stefano Noventa, Department of General Psychology  
- Prof. Giovanni Bruno, Department of General Psychology  
- Prof. Giorgio Arcara, Department of General Psychology  
- Prof. Fabio Masina, Department of General Psychology  
- Prof. Antonio Maffei, Department of Developmental and Social Psychology 
- Prof. Michele Vicovaro, Department of General Psychology
- Dr. Anna Panzeri, Department of General Psychology
- Dr. Luca Menghini, Department of General Psychology 
- Roberta Incardona, Department of Developmental and Social Psychology  
- Dr. Margherita Calderan, Department of General Psychology  
- Dr. Tommaso Feraco, Department of General Psychology  
- Dr. Filippo Gambarota, Department of Developmental and Social Psychology  
- Matteo Manente, Department of Developmental and Social Psychology  
- Ambra Perugini, Department of Developmental and Social Psychology  
- Prof. Enrico Toffalini, Department of General Psychology  
